

const ID = {
  RANDOM_TRIANGLES : 'RANDOM_TRIANGLES',
  CROWN : 'CROWN',
  PLANE : 'PLANE',
  CUBE : 'CUBE',
  TEXTURE_IMAGE : 'TEXTURE_IMAGE',
  CUBE_WITH_LIGHT : 'CUBE_WITH_LIGHT',
  CUBE_TRANSPARENT : 'CUBE_TRANSPARENT'
}

export default ID
