
export const ID_RANDOM_TRIANGLES = 'RANDOM_TRIANGLES'
export const ID_CROWN = 'CROWN'
export const ID_PLANE = 'PLANE'
export const ID_CUBE = 'CUBE'
export const ID_TEXTURE_IMAGE = 'TEXTURE_IMAGE'
export const ID_CUBE_WITH_LIGHT = 'CUBE_WITH_LIGHT'
export const ID_CUBE_TRANSPARENT = 'CUBE_TRANSPARENT'
